services:
  - type: web
    name: blog-horizon2
    env: java
    plan: free
    buildCommand: "./mvnw clean package" # or "mvn clean package" if you don't use wrapper
    startCommand: "java -jar target/*.jar"
    branch: main
    healthCheckPath: /
